---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: concession-kiosk-web
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: frontend
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        deployment: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: COMPONENT_BACKEND_HOST
              value: backend.concession-kiosk-app.svc.cluster.local
            - name: COMPONENT_BACKEND_PORT
              value: '8080'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
